package ru.stqa.pft.addressbook.tests;// Generated by Selenium IDE

import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

public class UserCreationTest {
  FirefoxDriver driver;


  @BeforeMethod
  public void setUp() {
    driver = new FirefoxDriver();
    //driver.manage().window().maximize();
    //driver.manage().timeouts().implicitlyWait(60, TimeUnit.SECONDS);
    driver.get("http://localhost/addressbook/");
    driver.findElement(By.id("LoginForm")).click();
    driver.findElement(By.name("user")).click();
    driver.findElement(By.name("user")).sendKeys("admin");
    driver.findElement(By.id("LoginForm")).click();
    driver.findElement(By.name("pass")).click();
    driver.findElement(By.name("pass")).sendKeys("secret");
    driver.findElement(By.cssSelector("input:nth-child(7)")).click();

  }

  @Test
  public void testUserCreation() {

    driver.findElement(By.linkText("add new")).click();
    driver.findElement(By.name("firstname")).click();
    driver.findElement(By.name("firstname")).sendKeys("Lena");
    driver.findElement(By.name("lastname")).sendKeys("Hidy");
    driver.findElement(By.name("address")).sendKeys("High street 11");
    driver.findElement(By.name("mobile")).sendKeys("090888888");
    driver.findElement(By.name("email")).sendKeys("9987@qwe.com");
    driver.findElement(By.name("bday")).click();
    {
      WebElement dropdown = driver.findElement(By.name("bday"));
      dropdown.findElement(By.xpath("//option[. = '29']")).click();
    }
    driver.findElement(By.cssSelector("select:nth-child(61) > option:nth-child(20)")).click();
    driver.findElement(By.name("bmonth")).click();
    {
      WebElement dropdown = driver.findElement(By.name("bmonth"));
      dropdown.findElement(By.xpath("//option[. = 'December']")).click();
    }
    driver.findElement(By.cssSelector("select:nth-child(62) > option:nth-child(13)")).click();
    driver.findElement(By.name("byear")).click();
    driver.findElement(By.name("byear")).sendKeys("1989");
    driver.findElement(By.cssSelector("input:nth-child(87)")).click();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
}